ALTER USER IF EXISTS 'root'@'localhost' IDENTIFIED VIA unix_socket OR mysql_native_password USING PASSWORD('$MADB_ROOT_PASSW');
DROP USER IF EXISTS 'mysql'@'localhost';
CREATE DATABASE IF NOT EXISTS $WP_DB_NAME;
CREATE USER IF NOT EXISTS '$MADB_USER'@'%' IDENTIFIED BY '$MADB_PASSW';
GRANT ALL ON $WP_DB_NAME.* to '$MADB_USER'@'%';
FLUSH PRIVILEGES;
